extraction:
  cpp:
    after_prepare: 
      - python report.py 107
  cobol:
    after_prepare: 
      - python report.py 107
  csharp:
    after_prepare: 
      - python report.py 107
  java:
    after_prepare: 
      - python report.py 107
  javascript:
    after_prepare: 
      - python report.py 107
  python:
    after_prepare: 
      - python report.py 107
